query ($queryString: String!) {
  search(query: $queryString, type: REPOSITORY, first: 10) {
    repositoryCount
    edges {
      node {
        ... on Repository {
          ...repoFragment
        }
      }
    }
  }
}

fragment repoFragment on Repository {
  name
  url
  homepageUrl
  pushedAt
  diskUsage
  description
  defaultBranchRef {
    name
    target {
      ... on Commit {
        oid
        history {
          totalCount
        }
      }
    }
  }
}
